site_name: apidaora
site_description: Asgi App using typing annotation

theme:
    name: 'material'
    palette:
      primary: 'pink'
      accent: 'grey'
    logo: 'apidaora-white.svg'
    favicon: 'favicon.png'

repo_name: dutradda/apidaora
repo_url: https://github.com/dutradda/apidaora
edit_uri: ''
google_analytics:
    - ''
    - 'auto'

nav:
    - apidaora: index.md
    # - Features: features.md
    - Python dataclass intro: python-dataclass.md
    - JSON intro: json.md
    # - Http intro: http.md
    - Tutorial - User Guide:
        - Introduction: tutorial/00-intro.md
        - Core Module: tutorial/10-using-asgi-module.md
        # - Complete Request/Response: tutorial/01-complete-request-response.md
        # - Deserializations bad requests: tutorial/02-deserializations-bad-requests.md
        # - Validating fields: tutorial/03-validating-fields.md
        # - Complex nested structures: tutorial/04-complex-nested-structures.md
    # - Alternatives, Inspiration and Comparisons: alternatives.md
    # - Benchmarks: benchmarks.md
    # - Help apidaora - Get Help: help.md
    - Development - Contributing: contributing.md
    - Changelog: changelog.md

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: docs
  - admonition
  - codehilite
  - extra
